### ISSUE TITLE
CRLF in `cli.js` cause error in Linux

### ISSUE THREAD

**Issue by mnghsn** [eight04/inline-js#3]
`cli.js` contains `CRLF` line endings by `npm install` and causes "No such file or directory" error under Linux. Maybe it's npm/npm#12371 issue.

**Comment by eight04** [comment]
Probably all my repos are affected by this. See https://github.com/eight04/sync-version/issues/1.

Also, according to https://github.com/npm/npm/issues/12371, you can resolve it by upgrading npm to 5.4.0+

**Comment by mnghsn** [comment]
Resolved by installing npm@^5.4.0. 👍
